import type { Metadata } from "next";
import { Inter, Zen_Kaku_Gothic_New } from "next/font/google";
import '@/styles/destyle.css'
import "@/styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });
const zen_kaku_gothic_new = Zen_Kaku_Gothic_New({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={zen_kaku_gothic_new.className}>{children}</body>
    </html>
  );
}
